spring:
  application:
    name: Parking
  session:
    jdbc:
      schema: classpath:org/springframework/session/jdbc/schema-postgresql.sql
      initialize-schema: always
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      data-locations: classpath:/sql/data.sql
      mode: always
